//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::budgets::Entity as Budgets;
pub use super::categories::Entity as Categories;
pub use super::otp_codes::Entity as OtpCodes;
pub use super::transactions::Entity as Transactions;
pub use super::users::Entity as Users;
